### ISSUE TITLE
unable to parse my i3 config

### ISSUE THREAD

**Issue by AUTplayed** [talwrii/i3parse#5]
```
[philipp@philipp ~]$ i3parse bindings
Traceback (most recent call last):
  File "/usr/bin/i3parse", line 11, in <module>
    load_entry_point('i3parse==0.1.0', 'console_scripts', 'i3parse')()
  File "/usr/lib/python3.6/site-packages/i3parse/i3parse.py", line 202, in main
    print_func(u'\n'.join(run(args)))
  File "/usr/lib/python3.6/site-packages/i3parse/i3parse.py", line 285, in run
    ast = parse(input_string)
  File "/usr/lib/python3.6/site-packages/i3parse/i3parse.py", line 321, in parse
    mac2unix(dos2unix(input_string)))
  File "/usr/lib/python3.6/site-packages/parsimonious/grammar.py", line 115, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/usr/lib/python3.6/site-packages/parsimonious/expressions.py", line 122, in parse
    raise IncompleteParseError(text, node.end, self)
parsimonious.exceptions.IncompleteParseError: Rule 'result' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with 'new_float normal

# ' (line 12, column 1).
```

**Comment by talwrii** [comment]
Thanks for the issue. Yeah... the i3 grammar is bigger than I thoughr.

If you were willing to send me your config file then we could avoid some back and forth while debugging this

See #3 for for high level plans for dealing with parsing.

**Comment by talwrii** [comment]
We now handle `new_float`: 88f7f20d81de84eb79a6ee07

**Comment by AUTplayed** [comment]
sure, here it is: https://github.com/AUTplayed/dotfiles/blob/master/.i3/config

**Comment by talwrii** [comment]
Ugh, why does everyone have to use shiny features :P?

- [ ] This depends on #4

**Comment by talwrii** [comment]
We now deal with border command: adfb7271

**Comment by adrianlzt** [comment]
These two portions also produce the same error
```
bindsym $mod+v split vertical

bar {
        #status_command i3status
        status_command /usr/bin/py3status --include ~/.config/i3status/
        #position top
        colors {
          background #d9d9d9
          statusline #000000
        }
}
```

The first one was easy: https://github.com/talwrii/i3parse/pull/9

Second one looks like more complicated.
